### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by dstansby** [wtbarnes/hinode-iris-2021-sunpy-tutorial#1]
- Sort the imports at in the first block
- Block 3: `.peek()` one of the maps?
- Block 4: Put arguments to `a.Time` on individual lines in block 4 to avoid a long line of code?
- Block 14: use `add_patch` instead of `add_artist` so the label shows up in the legend for the Sun
- Block 14: Why do you need `transform=ax.transProjectionAffine + ax.transAxes` ?
- Block 15: codestyle would say remember to put spaces after commas 😉 
- Block 17: add some single line comments and blank lines as whitespace, this big code block is confusing
- Block 17: The two figures look the same?? (although my adding comments might dispel this confusion)
- Block 17: the figures look very nice though!
- Block 155: Isn't there a `bottom_left_coord` map property you can use directly instead of the center one?
- Block 77: Use GONG instead of HMI for the magnetic field map? That way it's full Sun?
- Block 79: Bad practice to use `input` as a variable name as it's a builttin - use `pfss_input` instead. (sorry, I am 110% to blame for this, when pfsspy 1.0 finally happens this will be gone from my examples...)

**Comment by wtbarnes** [comment]
Thank you for this! I'm going to be working on this more this week, so I may have some follow up questions for you, especially given that this tutorial involves several of your pacakages!

**Comment by wtbarnes** [comment]
From Albert:

> Miscellaneous comments:
>
> * For your comparison of plotting EIS images before and after fixing the pointing, I suggest you change the titles or add text so it's clear what you are comparing
> * For your reprojection, you should specify the rsun frame attribute of frame_out to be equal to m_hmi.coordinate_frame.rsun, because that will stop stuff near the limb from being discarded
> * If you're using the developmental version of SunPy (or if 3.1 gets released), you can use GenericMap.reproject_to()
> * What does pfsspy.utils.car_to_cea() do? Can you simply reproject to CEA instead of CAR?

**Comment by wtbarnes** [comment]
# Checklist of Fixes

- [x] Sort the imports at in the first block
- [x] Block 3: .peek() one of the maps?
- [x] Block 4: Put arguments to a.Time on individual lines in block 4 to avoid a long line of code?
- [x] Block 14: use add_patch instead of add_artist so the label shows up in the legend for the Sun
- [ ] Block 14: Why do you need transform=ax.transProjectionAffine + ax.transAxes ?
- [x] Block 15: codestyle would say remember to put spaces after commas 😉
- [x] Block 17: add some single line comments and blank lines as whitespace, this big code block is confusing
- [x] Block 17: The two figures look the same?? (although my adding comments might dispel this confusion)
- [x] Block 17: the figures look very nice though!
- [x] Block 155: Isn't there a bottom_left_coord map property you can use directly instead of the center one?
- [ ] Block 77: Use GONG instead of HMI for the magnetic field map? That way it's full Sun?
- [x] Block 79: Bad practice to use input as a variable name as it's a builttin - use pfss_input instead. (sorry, I am 110% to blame for this, when pfsspy 1.0 finally happens this will be gone from my examples...)
- [x] For your comparison of plotting EIS images before and after fixing the pointing, I suggest you change the titles or add text so it's clear what you are comparing
- [x] For your reprojection, you should specify the rsun frame attribute of frame_out to be equal to m_hmi.coordinate_frame.rsun, because that will stop stuff near the limb from being discarded
- [x] If you're using the developmental version of SunPy (or if 3.1 gets released), you can use GenericMap.reproject_to()
- [ ] What does pfsspy.utils.car_to_cea() do? Can you simply reproject to CEA instead of CAR?
